version: '3.7'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    container_name: wp-mysql
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - ./wordpress/volume/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/volume/themes:/var/www/html/wp-content/themes
      - ./wordpress/volume/uploads:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: wp-mysql:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
    container_name: wp
